name: Get modified lines
on: [ pull_request ]

jobs:
  find_changed_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find changed lines
        id: changed_lines
        uses: hestonhoffman/changed-lines@v1
      - name: Print changed lines as json
        run: echo ${{ steps.changed_lines.outputs }}

      - name: Print changed lines2
        run: echo ${{ steps.changed_lines.outputs.changed_lines }}